### PR TITLE
Distribute rooms based on player count or room count

### PR DESCRIPTION
**Pull request by hunkydoryrepair**
This is one step toward improving load balancing, which is an option to load based on player count.

 Number of players is likely to change much more rapidly than # of rooms, so this limits how frequently it makes REDIS updates to avoid flooding REDIS servers. 

it also maintains the "roomcount" usage as long as your balancing mode is the default. Thus, it should not break existing apps. However, switching to player load balancing will use a different key in REDIS.

This works in the server init, with a new server option:
```
  const server = new Server({
    greet: false,
    balanceMode: BalanceMode.players
    presence,
    driver
  });
 ```
 
 default remains room balancing. 
 
 There is also a small bug fix. `remoteRoomCall` was not using  the `rejectionTimeout` argument in a meaningful way. Needs to be passed to `requestFromIPC`

### CODE REVIEW

**Comment by hunkydoryrepair** [comment]
This is actually not working right now in our tests because `MatchMaker.onClientJoinRoom` is not getting called

**Comment by hunkydoryrepair** [comment]
I've updated this PR with a fix to #633 and a few other fixes to keep the `join` and `leave` events to be equal. There were a number of places they are wrong:

- exception during onJoin or onAuth would cause 'leave' event to be fired without a 'join' event
- a reconnection would cause an extra 'join' event to be fired.

Added some more tests for:
- Client disconnecting during async onJoin (onLeave should be called AFTER onJoin completes)
- onJoin throwing exception (should not call onLeave)

**Comment by vitalyrotari** [comment]
You put to match attention on Redis optimization. Redis is the fastest in memory cache service, it can process millions of requests without any problems.  I build a game with vertical & horizontal scaling based on Colyseus + Redis, and I don't have any problems with performance or some bottlenecks, the number of players was 4-5k in same time, and the guaranty capacity was 10-12k of players. 

One more here, Redis driver is just an option, in case of Colyseus you can use another driver from the box or custom one. My opinion is to not garbage the core but improve it and make more customizable and flexible.

One of the bottlenecks on high loaded project will be the network bandwidth, and you must have separate load balancer which will distribute connections between clusters/servers.

**Comment by endel** [comment]
Thanks for your input @vitalyrotari, the ability to distribute rooms can be really useful in case of having room definitions with different `maxClients` configurations - the default behaviour of selecting the process with least amount of rooms within the cluster could not be optimal in certain scenarios. https://github.com/colyseus/colyseus/pull/654 now addresses this allowing the end-user to provide an option to customize this behaviour 🙌 

Thank you so much for raising this @hunkydoryrepair, and for the initial implementation

**Pull request closed without merging**
