### PR TITLE
attach ipv4 address while registering node.

### PR DESCRIPTION
**Pull request by abhang-atish**
**NPM** used : `public-ip`    **url**: https://www.npmjs.com/package/public-ip

### CODE REVIEW

**Comment by endel** [comment]
Thanks a lot for this @abhang-atish 🎉🎉 

In the future, it would be nice to replace `public-ip` with another solution, as the dependency tree of this package is quite enormous 🙈 

Screenshot 2019-09-09 at 09 40 24

**Comment by Yinmany** [comment]
External network IP is registered with redis, causing the agent to be unavailable.

**Comment by endel** [comment]
Hey @abhang-atish, have you also tried if using [`internal-ip`](https://www.npmjs.com/package/internal-ip) instead of [`public-ip`](https://www.npmjs.com/package/public-ip) works with the proxy?

**Comment by abhang-atish** [comment]
> Hey @abhang-atish, have you also tried if using [`internal-ip`](https://www.npmjs.com/package/internal-ip) instead of [`public-ip`](https://www.npmjs.com/package/public-ip) works with the proxy?

No not yet.

**Comment by abhang-atish** [comment]
> Hey @abhang-atish, have you also tried if using [`internal-ip`](https://www.npmjs.com/package/internal-ip) instead of [`public-ip`](https://www.npmjs.com/package/public-ip) works with the proxy?

hey @endel, I have tried `internal-ip`, and it works.

**Comment by endel** [comment]
Awesome, thanks for checking @abhang-atish, I've just replaced `public-ip` to use `internal-ip` on `colyseus@0.11.14`.

@Yinmany can you please check if it works for you with the proxy again?

Cheers!

**Pull request merged**
